#!/bin/bash

base=$1;
branch=$( \
  [ -z "$2" ] \
  && echo $(git symbolic-ref --short -q HEAD) \
  || echo $2 \
);

remote_url=$(git config --get remote.origin.url);

[[ $remote_url =~ github.com[/:](.*)\.git ]] && \
read user repo <<< $(echo ${BASH_REMATCH[1]//\// });

compare=$( \
  [ ! -z "$base" ] \
  && echo $base...$branch \
  || echo $branch \
);

git_url=https://github.com/$user/$repo/compare/$compare;

if which xdg-open > /dev/null
then
  xdg-open $gir_url
elif which gnome-open > /dev/null
then
  gnome-open $git_url
else
  open $git_url
fi
